### ISSUE TITLE
milliseconds..

### ISSUE THREAD

**Issue by warren-bank** [seiya-npm/ttml2srt#2]
example ttml input: `end="00:00:06.76"`

v1.1.0 output: `00:00:06,760`
v1.2.2 output: `00:00:06,076`

docs:
* [ttlm](https://www.w3.org/TR/2018/REC-ttml1-20181108/#timeExpression-syntax):
  - `.76` is a fraction of a second
  - equivalent to: `76/100 sec` == `760 ms`
* [srt](https://hungrytally.medium.com/beyond-the-subtitles-the-magic-of-srt-files-c4b99e042819#e93e)
  - `,760` denotes: `760 ms`
    * correct
  - `,076` denotes: `76 ms`
    * incorrect

comments:
* you just closed the [issue](https://github.com/warren-bank/node-ttml2srt-cli/issues/1)
  - I had completely forgotten about this repo
  - taking the hint, I just updated your library from v1.1.0 to v1.2.2
    * before making the commit, I ran a test and diffed the resulting output.. and noticed that every single timecode was wrong.. in the way described
* the problem appears to come from the implementation for [formatSrtTime](https://github.com/seiya-npm/ttml2srt/blob/d3f2444ed02f280bb6f2b110a752834f7e63d64f/main.js#L74)
  - the regex patterns are problematic
  - the strategy for applying '0' padding is the real culprit

**Comment by warren-bank** [comment]
actually.. I made the following change to correct this error:

[here](https://github.com/seiya-npm/ttml2srt/blob/d3f2444ed02f280bb6f2b110a752834f7e63d64f/main.js#L97-L100) is the existing code:
```javascript
    if (f[0] === '.') {
        let ms = f.substr(1).padStart(3, '0');
        return `${t[1]},${ms}`;
    }
```

..and this is the correction:
```javascript
    if (f[0] === '.') {
        let ms = f.substr(1).padEnd(3, '0');
        return `${t[1]},${ms}`;
    }
```

to summarize:
* change `padStart` to `padEnd` on line 98

**Comment by warren-bank** [comment]
final update..
I noticed in the diff of the code for my commit that v1.1.0 also used `padEnd`..
so I just went one step farther and reverted 2x lines of code in v1.2.2 to how they were in v1.1.0:

* line [90](https://github.com/seiya-npm/ttml2srt/blob/d3f2444ed02f280bb6f2b110a752834f7e63d64f/main.js#L90) to:<br>`let ms = Math.round((seconds - Math.floor(seconds)) * 1000).toString().padEnd(3, '0').substr(0, 3);`
* line [98](https://github.com/seiya-npm/ttml2srt/blob/d3f2444ed02f280bb6f2b110a752834f7e63d64f/main.js#L98) to:<br>`let ms = f.substr(1).padEnd(3, '0').substr(0, 3);`

**Comment by seiya-git** [comment]
@warren-bank, thanks! I pushed update to npm 
https://github.com/seiya-npm/ttml2srt/commit/58f71e5b1d5ba38621fc24e45b38d0ed45a6d09f

**Comment by warren-bank** [comment]
oops..
we missed one :disappointed: 

* line [107-108](https://github.com/seiya-npm/ttml2srt/blob/97c35724dbd74792170dda84d8546a47a5259ad8/main.js#L107-L108) to:
  ```javascript
    let ms = Math.floor(frames * 1000 / frameRate).toString().padEnd(3, '0').substr(0, 3);
    return `${t[1]},${ms}`;
  ``` 

I was super tired last night and somehow missed this. I'm very sorry!

**Comment by seiya-git** [comment]
@warren-bank, fixed

https://github.com/seiya-npm/ttml2srt/commit/797a625992897be2386f1ec669d2646bcd978461

**Comment by warren-bank** [comment]
thank you!
